{% set version = '1.6.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-msm
  version: {{ version|replace("-", "_") }}

source:
  fn: msm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/msm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/msm/msm_{{ version }}.tar.gz


  sha256: 1efe0117fe80962eb14ba434a521f5f870185c04e58864925cd4dfad1e4b1040
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: mstate,minqa,doParallel,foreach,numDeriv,testthat,flexsurv
requirements:
  build:
    - r-base 3.3.2
    - r-expm 0.999_2
    - r-mvtnorm 1.0_5
    - r-survival 2.40_1
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.3.2
    - r-expm 0.999_2
    - r-mvtnorm 1.0_5
    - r-survival 2.40_1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('msm')"  # [not win]
    - "\"%R%\" -e \"library('msm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=msm
  license: GPL (>= 2)
  summary: Functions for fitting continuous-time Markov and hidden Markov multi-state models
    to longitudinal data.  Designed for processes observed at arbitrary times in continuous
    time (panel data) but some other observation schemes are supported. Both Markov
    transition rates and the hidden Markov output process can be modelled in terms of
    covariates, which may be constant or piecewise-constant in time.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: msm
# Version: 1.6.4
# Date: 2016-10-02
# Title: Multi-State Markov and Hidden Markov Models in Continuous Time
# Author: Christopher Jackson <chris.jackson@mrc-bsu.cam.ac.uk>
# Maintainer: Christopher Jackson <chris.jackson@mrc-bsu.cam.ac.uk>
# Description: Functions for fitting continuous-time Markov and hidden Markov multi-state models to longitudinal data.  Designed for processes observed at arbitrary times in continuous time (panel data) but some other observation schemes are supported. Both Markov transition rates and the hidden Markov output process can be modelled in terms of covariates, which may be constant or piecewise-constant in time.
# License: GPL (>= 2)
# Imports: survival,mvtnorm,expm
# Suggests: mstate,minqa,doParallel,foreach,numDeriv,testthat,flexsurv
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2016-10-02 14:09:28 UTC; chris
# Repository: CRAN
# Date/Publication: 2016-10-04 14:33:52

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
