package:
  name: tesseract
  version: 3.05.00

source:
  fn: tesseract-3.05.00.tar.gz
  url: https://github.com/tesseract-ocr/tesseract/archive/3.05.00.tar.gz
  sha256: 3fe83e06d0f73b39f6e92ed9fc7ccba3ef734877b76aa5ddaaa778fac095d996

requirements:
  build:
    - gcc
    - automake
    - libtool
    - pkg-config
    - leptonica ==1.74.1
  run:
    - libgcc
    - leptonica ==1.74.1

test:
  commands:
    - tesseract -v

about:
  home: https://github.com/tesseract-ocr/tesseract
  summary: "Tesseract Open Source OCR Engine"
  license: Apache License 2.0
