package:
  name: tesseract
  version: "3.05.01"

source:
  git_url: https://github.com/tesseract-ocr/tesseract
  git_tag: 3.05.01

build:
  number: 1

requirements:
  build:
    - gcc ==5.4.0
    - automake
    - curl
    - libtool
    - pkg-config
    - leptonica ==1.74.4
  run:
    - libgcc >=5.4.0
    - leptonica ==1.74.4

test:
  files:
    - test.png
  commands:
    - tesseract -v
    - tesseract test.png stdout | grep "^joy of data$"

about:
  home: https://github.com/tesseract-ocr/tesseract
  summary: "Tesseract Open Source OCR Engine"
  license: Apache License 2.0
