{% set version = "2.36.11" %}

package:
  name: gdk-pixbuf
  version: {{ version }}

source:
  fn:  gdk-pixbuf-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.11.tar.xz
  sha256: ae62ab87250413156ed72ef756347b10208c00e76b222d82d9ed361ed9dde2f3

requirements:
  build:
    - gcc ==5.4.0 # [linux]
    - pkg-config
    - cairo ==1.14.10
    - glib ==2.53.6
    - gobject-introspection ==1.53.5
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - jpeg ==8d
    - pango ==1.40.11
    - shared-mime-info ==1.8
  run:
    - libgcc >=5.4.0 # [linux]
    - cairo ==1.14.10
    - glib ==2.53.6
    - gobject-introspection ==1.53.5
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - jpeg ==8d
    - pango ==1.40.11
    - shared-mime-info ==1.8

about:
  home: https://gtk.org
  license: LGPLv2
  license_file: COPYING
  summary: Toolkit for image loading and pixel buffer manipulation
