{% set version = '2.1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gbm
  version: {{ version|replace("-", "_") }}

source:
  fn: gbm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gbm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gbm/gbm_{{ version }}.tar.gz


  sha256: eaf24be931d762f1ccca4f90e15997719d01005f152160a3d20d858a0bbed92b
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit
requirements:
  build:
    - gcc ==5.4.0
    - r-base ==3.3.2
    - r-lattice ==0.20_34
    - r-survival ==2.40_1

  run:
    - libgcc >=5.4.0
    - r-base ==3.3.2
    - r-lattice ==0.20_34
    - r-survival ==2.40_1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gbm')"  # [not win]
    - "\"%R%\" -e \"library('gbm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://code.google.com/p/gradientboostedmodels/
  license: GPL (>= 2) | file LICENSE
  summary: An implementation of extensions to Freund and Schapire's AdaBoost algorithm and Friedman's
    gradient boosting machine. Includes regression methods for least squares, absolute
    loss, t-distribution loss, quantile regression, logistic, multinomial logistic,
    Poisson, Cox proportional hazards partial likelihood, AdaBoost exponential loss,
    Huberized hinge loss, and Learning to Rank measures (LambdaMart).
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: gbm
# Version: 2.1.3
# Date: 2017-03-21
# Title: Generalized Boosted Regression Models
# Author: Greg Ridgeway <gregridgeway@gmail.com> with contributions from others
# Maintainer: ORPHANED
# Depends: R (>= 2.9.0), survival, lattice, splines, parallel
# Suggests: RUnit
# Description: An implementation of extensions to Freund and Schapire's AdaBoost algorithm and Friedman's gradient boosting machine. Includes regression methods for least squares, absolute loss, t-distribution loss, quantile regression, logistic, multinomial logistic, Poisson, Cox proportional hazards partial likelihood, AdaBoost exponential loss, Huberized hinge loss, and Learning to Rank measures (LambdaMart).
# License: GPL (>= 2) | file LICENSE
# URL: http://code.google.com/p/gradientboostedmodels/
# Packaged: 2017-03-21 06:44:01 UTC; ripley
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2017-03-21 06:48:03 UTC
# X-CRAN-Original-Maintainer: Harry Southworth <harry.southworth@gmail.com>
# X-CRAN-Comment: Orphaned on 2017-03-21 as long-standing errors were not corrected.  NMU by CRAN team.

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
