{% set version = '0.9-25' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kernlab
  version: {{ version|replace("-", "_") }}

source:
  fn: kernlab_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/kernlab_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/kernlab/kernlab_{{ version }}.tar.gz


  sha256: b9de072754bb03c02c4d6a5ca20f2290fd090de328b55ab334ac0b397ac2ca62
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc ==5.4.0                  # [not win]

  run:
    - r-base 3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kernlab')"  # [not win]
    - "\"%R%\" -e \"library('kernlab')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=kernlab
  license: GPL-2
  summary: Kernel-based machine learning methods for classification, regression, clustering,
    novelty detection, quantile regression and dimensionality reduction.  Among other
    methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel
    PCA, Gaussian Processes and a QP solver.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: kernlab
# Version: 0.9-25
# Title: Kernel-Based Machine Learning Lab
# Authors@R: c(person("Alexandros", "Karatzoglou", role = c("aut", "cre"), email = "alexandros.karatzoglou@gmail.com"), person("Alex", "Smola", role = "aut"), person("Kurt", "Hornik", role = "aut"))
# Description: Kernel-based machine learning methods for classification, regression, clustering, novelty detection, quantile regression and dimensionality reduction.  Among other methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel PCA, Gaussian Processes and a QP solver.
# Depends: R (>= 2.10)
# Imports: methods, stats, grDevices, graphics
# LazyLoad: Yes
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2016-10-03 06:52:15 UTC; hornik
# Author: Alexandros Karatzoglou [aut, cre], Alex Smola [aut], Kurt Hornik [aut]
# Maintainer: Alexandros Karatzoglou <alexandros.karatzoglou@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-10-03 09:43:44

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
