package:
  name: flask-cache
  version: "0.13.1"

source:
  fn: Flask-Cache-0.13.1.tar.gz
  url: https://pypi.python.org/packages/91/c4/f71095437bd4b691c63f240e72a20c57e2c216085cbc271f79665885d3da/Flask-Cache-0.13.1.tar.gz
  md5: ab82a9cd0844891ccdb54fbb93fd6c59

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - flask ==0.12.2
  run:
    - python
    - flask ==0.12.2

test:
  # Python imports
  imports:
    - flask_cache

about:
  home: http://github.com/thadeusb/flask-cache
  license: BSD License
  summary: 'Adds cache support to your Flask application'
  license_family: BSD
