{% set base_version = "5.20.3" %}
{% set version = base_version + ".1" %}


package:
  name: perl
  version: {{ version }}

source:
  fn: perl-{{ base_version }}.tar.gz                                                                       # [unix]
  url: http://www.cpan.org/src/5.0/perl-{{ base_version }}.tar.gz                                          # [unix]
  sha1: 1091d56b81c1060601d5228fd42ad5cf10546622                                                           # [unix]

build:
  number: 0

test:
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic License
  license_family: Other
  license: Perl
  summary: "The Perl programming language interpreter."


extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
