{% set version = '1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prroc
  version: {{ version|replace("-", "_") }}

source:
  fn: PRROC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/PRROC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/PRROC/PRROC_{{ version }}.tar.gz


  sha256: cccb0d4c02e756054fb1ed75ba21714618b278e67b25452be124124c45821b0e
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, ggplot2
requirements:
  build:
    - r-base ==3.3.2

  run:
    - r-base ==3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('PRROC')"  # [not win]
    - "\"%R%\" -e \"library('PRROC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=PRROC
  license: GPL-3
  summary: 'Computes the areas under the precision-recall (PR) and ROC curve for weighted (e.g.,
    soft-labeled) and unweighted data. In contrast to other implementations, the interpolation
    between points of the PR curve is done by a non-linear piecewise function. In addition
    to the areas under the curves, the curves themselves can also be computed and plotted
    by a specific S3-method. References: Davis and Goadrich (2006) <doi:10.1145/1143844.1143874>;
    Keilwagen et al. (2014) <doi:10.1371/journal.pone.0092209>; Grau et al. (2015) <doi:10.1093/bioinformatics/btv153>.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: PRROC
# Type: Package
# Title: Precision-Recall and ROC Curves for Weighted and Unweighted Data
# Version: 1.3
# Date: 2017-04-21
# Author: Jan Grau and Jens Keilwagen
# Maintainer: Jan Grau <grau@informatik.uni-halle.de>
# Description: Computes the areas under the precision-recall (PR) and ROC curve for weighted (e.g., soft-labeled) and unweighted data. In contrast to other implementations, the interpolation between points of the PR curve is done by a non-linear piecewise function. In addition to the areas under the curves, the curves themselves can also be computed and plotted by a specific S3-method. References: Davis and Goadrich (2006) <doi:10.1145/1143844.1143874>; Keilwagen et al. (2014) <doi:10.1371/journal.pone.0092209>; Grau et al. (2015) <doi:10.1093/bioinformatics/btv153>.
# License: GPL-3
# Packaged: 2017-04-21 15:13:53 UTC; dev
# Suggests: testthat, ggplot2
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2017-04-21 18:46:33 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
