package:
  name: gsnap
  version: "2017.01.14"
source:
  fn: gmap-gsnap-2017-01-14.tar.gz
  url: http://research-pub.gene.com/gmap/src/gmap-gsnap-2017-01-14.tar.gz
  md5: 5940db8cba075310009fe4c55e0aeda1
requirements:
  build:
    - perl 5.20.3.1
    - zlib
    - binutils 2.25*
  run:
    - perl 5.20.3.1
    - zlib
    - binutils 2.25*
about:
  home: http://research-pub.gene.com/gmap/
  license: Non-commercial
  summary: Genomic mapping and alignment program for mRNA and EST sequences
build:
  number: 0
  skip: True # [osx]
  binary_has_prefix_files:
    - bin/atoiindex
    - bin/cmetindex
    - bin/get-genome
    - bin/gmap.avx2
    - bin/gmap.nosimd
    - bin/gmapl.avx2
    - bin/gmapl.nosimd
    - bin/gsnap.avx2
    - bin/gsnap.nosimd
    - bin/gsnapl.avx2
    - bin/gsnapl.nosimd
    - bin/sam_sort
    - bin/snpindex
    - bin/uniqscan
    - bin/uniqscanl
  has_prefix_files:
    - bin/gff3_introns
    - bin/gff3_splicesites
    - bin/gmap_build
    - bin/gmap_uncompress
    - bin/gtf_introns
    - bin/gtf_splicesites
test:
  commands: 
    - gmap --version
    - gsnap --version
