package:
  name: ete3
  version: 3.0.0b35

source:
  url: https://pypi.python.org/packages/f0/c5/e1bb20c02f0e7cd924eab783901b4e2acf8fda79c0f7c7303b740bf7b98e/ete3-3.0.0b35.tar.gz
  md5: f4797833ba9afc8547061bfda286c6f5

requirements:
  build:
    - python
  run:
    - python
    - six

test:
  imports:
    - ete3

about:
  home: http://etetoolkit.org/
  license: GPLv3
  summary: A Python Environment for (phylogenetic) Tree Exploration
