package:
  name: fftw
  version: "3.3.7"

source:
  url: http://fftw.org/fftw-3.3.7.tar.gz
  md5: 0d5915d7d39b3253c1cc05030d79ac47

requirements:
  build:
    - gcc ==5.4.0
  run:
    - libgcc >=5.4.0

about:
    home: http://fftw.org
    license: GPLv3
    summary: 'The fastest Fourier transform in the west.'
