{% set version = '1.1-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastmatch
  version: {{ version|replace("-", "_") }}

source:
  fn: fastmatch_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fastmatch_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fastmatch/fastmatch_{{ version }}.tar.gz


  sha256: 20b51aa4838dbe829e11e951444a9c77257dcaf85130807508f6d7e76797007d
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fastmatch')"  # [not win]
    - "\"%R%\" -e \"library('fastmatch')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/fastmatch
  license: GPL-2
  summary: Package providing a fast match() replacement for cases that require repeated look-ups.
    It is slightly faster that R's built-in match() function on first match against
    a table, but extremely fast on any subsequent lookup as it keeps the hash table
    in memory.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: fastmatch
# Version: 1.1-0
# Title: Fast match() function
# Author: Simon Urbanek <simon.urbanek@r-project.org>
# Maintainer: Simon Urbanek <simon.urbanek@r-project.org>
# Description: Package providing a fast match() replacement for cases that require repeated look-ups. It is slightly faster that R's built-in match() function on first match against a table, but extremely fast on any subsequent lookup as it keeps the hash table in memory.
# License: GPL-2
# URL: http://www.rforge.net/fastmatch
# NeedsCompilation: yes
# Packaged: 2017-01-28 14:18:51 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2017-01-28 17:37:09

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
