package:
  name: smalt
  version: "0.7.6"

source:
  fn: smalt-0.7.6-static.tar.gz
  url: https://sourceforge.net/projects/smalt/files/smalt-0.7.6-static.tar.gz
  md5: 57ed011836fda8fb5e34604dd1858b5e

requirements:
  build:
    - gcc
    - libtool
    - pkg-config
    - zlib
    - bambamc ==0.0.50
    - python >=2.6,<3   # used by 'make check'
    - samtools          # used by 'make check'
  run:
    - libgcc
    - bambamc ==0.0.50
    - zlib

test:
  commands:
    - smalt version 2>&1 | grep "SMALT - Sequence Mapping and Alignment Tool" > /dev/null

about:
  home: http://www.sanger.ac.uk/science/tools/smalt-0
  license: GPLv3
  summary: SMALT aligns DNA sequencing reads with a reference genome.
