package:
  name: jsonlines
  version: "1.2.0"

source:
  fn: jsonlines-1.2.0.tar.gz
  url: https://pypi.python.org/packages/90/cd/0beacbcfdf9b3af9e7c615cb3dba7ec4be1030d4b283e3c9717e3fd9af3c/jsonlines-1.2.0.tar.gz
  md5: 05f0f16ed7320a6040a9c181623774de
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jsonlines = jsonlines:main
    #
    # Would create an entry point called jsonlines that calls jsonlines.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six ==1.10

  run:
    - python
    - six ==1.10

test:
  # Python imports
  imports:
    - jsonlines

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wbolster/jsonlines
  license: BSD License
  summary: 'Library with helpers for the jsonlines file format'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
