{% set name = "nbdime" %}
{% set version = "0.3.0" %}
{% set sha256 = "db44124bf5a8a00ff5ec36d4678fa18aa7ad15244948f3a09ab8dfd5a49a9ca2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - nbdime=nbdime.__main__:main_dispatch
    - nbshow=nbdime.nbshowapp:main
    - nbdiff=nbdime.nbdiffapp:main
    - nbdiff-web=nbdime.webapp.nbdiffweb:main
    - nbmerge=nbdime.nbmergeapp:main
    - nbmerge-web=nbdime.webapp.nbmergeweb:main
    - git-nbdifftool=nbdime.gitdifftool:main
    - git-nbmergetool=nbdime.gitmergetool:main
    - git-nbdiffdriver=nbdime.gitdiffdriver:main
    - git-nbmergedriver=nbdime.gitmergedriver:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - nbformat 4.4.0
    - six 1.10.0
    - colorama 0.3.9
    - tornado 4.5.2
    - requests
    - gitpython 2.1.3
    - backports.functools_lru_cache  # [py2k]
    - backports.shutil_which  # [py2k]

test:
  imports:
    - nbdime
  commands:
    - nbdime show -h
    - nbshow -h
    - nbdiff -h
    - nbdiff-web -h
    - nbmerge -h
    - nbmerge-web -h
    - git-nbdifftool -h
    - git-nbmergetool -h
    - git-nbdiffdriver -h
    - git-nbmergedriver -h

about:
  home: https://nbdime.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Diff and merge of Jupyter Notebooks'
  doc_url: https://nbdime.readthedocs.io/
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
    - ocefpaf
