package:
  name: mummer
  version: "3.23"

source:
  fn: mummer-3.23.tar.gz
  sha256: 1efad4f7d8cee0d8eaebb320a2d63745bb3a160bb513a15ef7af46f330af662f
  url: https://downloads.sourceforge.net/project/mummer/mummer/3.23/MUMmer3.23.tar.gz

requirements:
  build:
    - perl 5.22.2.1
  run:
    - perl 5.22.2.1

test:
  commands:
    - mummer -h &>/dev/null
    - mummerplot -h &>/dev/null
    - nucmer -h &>/dev/null
    - promer -h &>/dev/null
    - show-aligns -h &>/dev/null

about:
  home: http://mummer.sourceforge.net
  license: The Artistic License
  summary: MUMmer is a system for rapidly aligning entire genomes
