{% set version = '0.3-40' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scatterplot3d
  version: {{ version|replace("-", "_") }}

source:
  fn: scatterplot3d_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/scatterplot3d_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/scatterplot3d/scatterplot3d_{{ version }}.tar.gz


  sha256: 8249118aa29199017a6686d8245fed5343dabcf049b1588141a7cf83245b6a29
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2

  run:
    - r-base 3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('scatterplot3d')"  # [not win]
    - "\"%R%\" -e \"library('scatterplot3d')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=scatterplot3d
  license: GPL-2
  summary: Plots a three dimensional (3D) point cloud.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: scatterplot3d
# Version: 0.3-40
# Date: 2017-04-22
# Title: 3D Scatter Plot
# Author: Uwe Ligges <ligges@statistik.tu-dortmund.de>, Martin Maechler, Sarah Schnackenberg
# Maintainer: Uwe Ligges <ligges@statistik.tu-dortmund.de>
# Description: Plots a three dimensional (3D) point cloud.
# Depends: R (>= 2.7.0)
# License: GPL-2
# Encoding: latin1
# Imports: grDevices, graphics, stats
# NeedsCompilation: no
# Packaged: 2017-04-22 15:51:29 UTC; ligges
# Repository: CRAN
# Date/Publication: 2017-04-22 16:17:10 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
