{% set name = 'plotROC' %}
{% set version = '2.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat, stringr, survivalROC, rmarkdown
requirements:
  build:
    - r-base 3.3.2
    - r-ggplot2 2.2.0
    - r-gridsvg 1.5_1
    - r-plyr 1.8.4
    - r-shiny 0.14.2

  run:
    - r-base 3.3.2
    - r-ggplot2 2.2.0
    - r-gridsvg 1.5_1
    - r-plyr 1.8.4
    - r-shiny 0.14.2
test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('plotROC')"  # [not win]
    - "\"%R%\" -e \"library('plotROC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://sachsmc.github.io/plotROC
  license: MIT + file LICENSE
  summary: Most ROC curve plots obscure the cutoff values and inhibit interpretation and comparison
    of multiple curves. This attempts to address those shortcomings by providing plotting
    and interactive tools. Functions are provided to generate an interactive ROC curve
    plot for web use, and print versions. A Shiny application implementing the functions
    is also included.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: plotROC
# Type: Package
# Title: Generate Useful ROC Curve Charts for Print and Interactive Use
# Version: 2.2.0
# Date: 2017-08-09
# Authors@R: c(person("Michael C.", "Sachs", role = c("aut", "cre"), email = "sachsmc@gmail.com"), person("Robert W.", "Corty", role = "ctb", email = "rcorty@gmail.com"))
# Maintainer: Michael C. Sachs <sachsmc@gmail.com>
# Description: Most ROC curve plots obscure the cutoff values and inhibit interpretation and comparison of multiple curves. This attempts to address those shortcomings by providing plotting and interactive tools. Functions are provided to generate an interactive ROC curve plot for web use, and print versions. A Shiny application implementing the functions is also included.
# License: MIT + file LICENSE
# URL: http://sachsmc.github.io/plotROC
# BugReports: http://github.com/sachsmc/plotROC/issues
# Depends: R (>= 3.0.0), ggplot2
# Imports: methods, grid, gridSVG, shiny, plyr
# Suggests: knitr, testthat, stringr, survivalROC, rmarkdown
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-08-09 14:21:29 UTC; micsac
# Author: Michael C. Sachs [aut, cre], Robert W. Corty [ctb]
# Repository: CRAN
# Date/Publication: 2017-08-09 17:21:59 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
