package:
  name: bzip2
  version: 1.0.6

source:
  fn: bzip2-1.0.6.tar.gz
  url: http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
  md5: 00b516f4704d4a7cb50a1d97e6e8e15b

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - bzip2 --help

about:
  home: http://www.bzip.org/
  summary: high-quality data compressor
  license: BSD
  license_file: LICENSE
