package:
  name: cx_oracle
  version: "5.3"

source:
  fn: cx_Oracle-5.3.tar.gz
  url: https://github.com/oracle/python-cx_Oracle/archive/5.3.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  # Python imports
  imports:
    - cx_Oracle

about:
  home: https://github.com/oracle/python-cx_Oracle
  license: BSD 
  summary: 'Python interface to Oracle Database'
