{% set version = '0.5-23.1097' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lavaan
  version: {{ version|replace("-", "_") }}

source:
  fn: lavaan_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lavaan_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lavaan/lavaan_{{ version }}.tar.gz


  sha256: 9aa7c3278f08f46b91fb0357dbdb9539936ba54e11d270d7febce0049efc9d87
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog

  run:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lavaan')"  # [not win]
    - "\"%R%\" -e \"library('lavaan')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://lavaan.org
  license: GPL (>= 2)
  summary: Fit a variety of latent variable models, including confirmatory factor analysis, structural
    equation modeling and latent growth curve models.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: lavaan
# Title: Latent Variable Analysis
# Version: 0.5-23.1097
# Authors@R: c(person(given = "Yves", family = "Rosseel", role  = c("aut", "cre"), email = "Yves.Rosseel@UGent.be"), person(given = "Daniel", family = "Oberski", role = "ctb", email = "daniel.oberski@gmail.com"), person(given = "Jarrett", family = "Byrnes",  role = "ctb", email = "byrnes@nceas.ucsb.edu"), person(given = "Leonard", family = "Vanbrabant", role = "ctb", email = "Leonard.Vanbrabant@ugent.be"), person(given = "Victoria", family = "Savalei", role = "ctb", email = "vsavalei@ubc.ca"), person(given = "Ed", family = "Merkle", role = "ctb", email = "merklee@missouri.edu"), person(given = "Michael", family = "Hallquist", role = "ctb", email = "michael.hallquist at gmail.com"), person(given = "Mijke", family = "Rhemtulla", role = "ctb", email = "mijke@ku.edu"), person(given = "Myrsini", family = "Katsikatsou", role = "ctb", email = "mirtok2@gmail.com"), person(given = "Mariska", family = "Barendse", role = "ctb", email = "m.t.barendse@rug.nl"), person(given = "Michael", family = "Chow", role = "ctb", email = "machow@princeton.edu"), person(given = "Terrence", family = "Jorgensen", role = "ctb") )
# Description: Fit a variety of latent variable models, including confirmatory factor analysis, structural equation modeling and latent growth curve models.
# Depends: R(>= 3.1.0)
# Imports: methods, stats4, stats, utils, graphics, MASS, mnormt, pbivnorm, quadprog, numDeriv
# Suggests: testthat
# License: GPL (>= 2)
# LazyData: yes
# URL: http://lavaan.org
# NeedsCompilation: no
# Packaged: 2017-02-24 13:08:31 UTC; yves
# Author: Yves Rosseel [aut, cre], Daniel Oberski [ctb], Jarrett Byrnes [ctb], Leonard Vanbrabant [ctb], Victoria Savalei [ctb], Ed Merkle [ctb], Michael Hallquist [ctb], Mijke Rhemtulla [ctb], Myrsini Katsikatsou [ctb], Mariska Barendse [ctb], Michael Chow [ctb], Terrence Jorgensen [ctb]
# Maintainer: Yves Rosseel <Yves.Rosseel@UGent.be>
# Repository: CRAN
# Date/Publication: 2017-02-24 23:28:29

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
