package:
  name: geopandas
  version: "0.2.1"

source:
  fn: geopandas-0.2.1.tar.gz
  url: https://pypi.python.org/packages/02/5a/62ba0dc9cf9b10071e3552fe00ced345cc56ca2a97d95ce63e5e3a7e179b/geopandas-0.2.1.tar.gz
  md5: a626ed98e305cbc023afa2d299e5e521
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - geopandas = geopandas:main
    #
    # Would create an entry point called geopandas that calls geopandas.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas 0.20.2
    - shapely 1.5.16
    - fiona 1.7.3
    - descartes 1.1.0
    - pyproj 1.9.5.1

  run:
    - python
    - pandas 0.20.2
    - shapely 1.5.16
    - fiona 1.7.3
    - descartes 1.1.0
    - pyproj 1.9.5.1

test:
  # Python imports
  imports:
    - geopandas
    - geopandas.datasets
    - geopandas.io
    - geopandas.tools

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://geopandas.org
  license: BSD
  summary: 'Geographic pandas extensions'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
