package:
  name: iva
  version: "1.0.8"

source:
  git_url: https://github.com/sanger-pathogens/iva
  git_tag: v1.0.8

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
    - fastaq ==3.15.0
    - kmc ==3.0.0
    - mummer ==3.23
    - networkx ==1.11
    - pysam ==0.12.0.1
    - samtools ==1.3.1
    - smalt ==0.7.6
  run:
    - python
    - fastaq ==3.15.0
    - kmc ==3.0.0
    - mummer ==3.23
    - networkx ==1.11
    - pysam ==0.12.0.1
    - samtools ==1.3.1
    - smalt ==0.7.6

test:
  commands:
    - iva --version

about:
  home: https://github.com/sanger-pathogens/iva
  license: GPLv3
  summary: de novo virus assembler of Illumina paired reads
  license_file: LICENSE
