{% set version = '0.1-20' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggdendro
  version: {{ version|replace("-", "_") }}

source:
  fn: ggdendro_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggdendro_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggdendro/ggdendro_{{ version }}.tar.gz


  sha256: 125cae904fa5d426cccaf32ebe9c6297e9ef0c6fd3f19f61513834d03a0cf8ff
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rpart(>= 4.0-0), tree, testthat, knitr, cluster, scales
requirements:
  build:
    - r-base 3.3.2
    - r-mass 7.3_45
    - r-ggplot2 2.2.0

  run:
    - r-base 3.3.2
    - r-mass 7.3_45
    - r-ggplot2 2.2.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggdendro')"  # [not win]
    - "\"%R%\" -e \"library('ggdendro')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/andrie/ggdendro
  license: GPL-2 | GPL-3
  summary: This is a set of tools for dendrograms and tree plots using 'ggplot2'.  The 'ggplot2'
    philosophy is to clearly separate data from the presentation. Unfortunately the
    plot method for dendrograms plots directly to a plot device without exposing the
    data. The 'ggdendro' package resolves this by making available functions that extract
    the dendrogram plot data. The package provides implementations for tree, rpart,
    as well as diana and agnes cluster diagrams.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: ggdendro
# Authors@R: c(person("Andrie", "de Vries", role=c("aut", "cre"), email="apdevries@gmail.com"), person(c("Brian", "D."), "Ripley", role = c("aut"), comment = "author of package tree"))
# License: GPL-2 | GPL-3
# Title: Create Dendrograms and Tree Diagrams Using 'ggplot2'
# LazyData: true
# LazyLoad: true
# ByteCompile: true
# Description: This is a set of tools for dendrograms and tree plots using 'ggplot2'.  The 'ggplot2' philosophy is to clearly separate data from the presentation. Unfortunately the plot method for dendrograms plots directly to a plot device without exposing the data. The 'ggdendro' package resolves this by making available functions that extract the dendrogram plot data. The package provides implementations for tree, rpart, as well as diana and agnes cluster diagrams.
# Version: 0.1-20
# URL: https://github.com/andrie/ggdendro
# BugReports: https://github.com/andrie/ggdendro/issues
# Date: 2016-04-27
# Imports: MASS, ggplot2(>= 0.9.2)
# Suggests: rpart(>= 4.0-0), tree, testthat, knitr, cluster, scales
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-04-27 10:47:14 UTC; adevries
# Author: Andrie de Vries [aut, cre], Brian D. Ripley [aut] (author of package tree)
# Maintainer: Andrie de Vries <apdevries@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-04-27 18:28:33

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
