{% set version = '1.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rwty
  version: {{ version|replace("-", "_") }}

source:
  fn: rwty_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rwty_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rwty/rwty_{{ version }}.tar.gz


  sha256: b5bb19cf11cf6baf3442e0affde56daa7736a0b211032a32dd4a22bb1895c6f0
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr,
requirements:
  build:
    - r-base 3.3.2
    - r-ggally 1.3.0
    - r-ape 4.1
    - r-coda 0.18_1
    - r-ggdendro 0.1_20
    - r-ggplot2 2.2.0
    - r-phangorn 2.2.0
    - r-plyr 1.8.4
    - r-reshape2 1.4.2
    - r-viridis 0.3.4

  run:
    - r-base 3.3.2
    - r-ggally 1.3.0
    - r-ape 4.1
    - r-coda 0.18_1
    - r-ggdendro 0.1_20
    - r-ggplot2 2.2.0
    - r-phangorn 2.2.0
    - r-plyr 1.8.4
    - r-reshape2 1.4.2
    - r-viridis 0.3.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rwty')"  # [not win]
    - "\"%R%\" -e \"library('rwty')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rwty
  license: GPL-2
  summary: Implements various tests, visualizations, and metrics for diagnosing convergence of
    MCMC chains in phylogenetics.  It implements and automates many of the functions
    of the AWTY package in the R environment.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: rwty
# Type: Package
# Title: R We There Yet? Visualizing MCMC Convergence in Phylogenetics
# Version: 1.0.1
# Author: Dan Warren <dan.l.warren@gmail.com>, Anthony Geneva <anthony.geneva@gmail.com>, Rob Lanfear <rob.lanfear@gmail.com>
# Maintainer: Dan Warren <dan.l.warren@gmail.com>
# Description: Implements various tests, visualizations, and metrics for diagnosing convergence of MCMC chains in phylogenetics.  It implements and automates many of the functions of the AWTY package in the R environment.
# License: GPL-2
# Depends: R (>= 3.3.0), ape, ggplot2,
# Imports: reshape2, phangorn, coda, viridis, grid, plyr, ggdendro, GGally, parallel,
# Suggests: knitr,
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-06-20 21:20:14 UTC; danwarren
# Repository: CRAN
# Date/Publication: 2016-06-22 05:42:18

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
