package:
  name: xgboost
  version: 0.7

source:
  git_url: https://github.com/dmlc/xgboost
  git_tag: v0.7

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgcc-ng
  host:
    - python
    - setuptools
    - numpy ==1.13.0
    - scipy ==0.19.0
  run:
    - python
    - setuptools
    - numpy ==1.13.0
    - scipy ==0.19.0

test:
  imports:
    - xgboost

about:
  home: https://github.com/dmlc/xgboost
  summary: eXtreme Gradient Boosting
  license: Apache 2.0
  license_file: LICENSE
