package:
  name: fastx_toolkit
  version: 0.0.14

source:
  fn: fastx_toolkit-0.0.14.tar.bz2
  url: https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2
  sha1: d8434af2dd647e303506a54ab14fe667aabc1a86

requirements:
  build:
    - gcc
    - pkg-config
    - libgtextutils
  run:
    - libgcc
    - libgtextutils

test:
  commands:
    - fastx_trimmer -h | grep "Part of FASTX Toolkit 0.0.14 by A. Gordon (assafgordon@gmail.com)"

about:
  home: https://github.com/agordon/fastx_toolkit
  license: AGPL
  summary: FASTA/FASTQ pre-processing programs
