about:
    home: http://subread.sourceforge.net/
    license: GPLv3
    summary: High-performance read alignment, quantification, and mutation discovery
package:
    name: subread
    version: 1.5.3

build:
  number: 0
source:
    fn: subread-1.5.3-source.tar.gz                                                               # [linux64]
    #url: https://sourceforge.net/projects/subread/files/subread-1.5.3/subread-1.5.3-Linux-x86_64.tar.gz  # [linux64]
    #md5: 33b725e2a34b9b54922b9dfa9e54ced2 # [linux64]
    url: https://downloads.sourceforge.net/project/subread/subread-1.5.3/subread-1.5.3-source.tar.gz # {linux64]
    md5: 05a37bbfdc36c2af46a0ce17c1f13367 # [linux64]
    #fn: subread-1.5.3-MacOSX-x86_64.tar.gz                                                              # [osx]
    #url: https://sourceforge.net/projects/subread/files/subread-1.5.3/subread-1.5.3-MacOSX-x86_64.tar.gz # [osx]
    #md5: d1d9d05226484a1df184f7ef6d541ffa # [osx]

requirements:
  build:
    - zlib
    - gcc
  run:
    - zlib
    - gcc
test:
    commands:
        - featureCounts -v 2>&1 > /dev/null
