package:
  name: pll
  version: 1.0.11

source:
  fn: libpll-1.0.11.tar.gz
  url: http://www.libpll.org/Downloads/libpll-1.0.11.tar.gz
  sha256: 1fb7af4d09bb935b0cc6c4d0ddff21a29ceff38c401328543d1639299ea31ec1

requirements:
  build:
    - gcc   # [not osx]
  run:
    - libgcc    # [not osx]

test:
#  commands:

about:
  home: http://www.libpll.org
  license: GPLv3
  summary: Phylogenetic Likelihood Library
