{% set version = '1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glmnetutils
  version: {{ version|replace("-", "_") }}

source:
  fn: glmnetUtils_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/glmnetUtils_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/glmnetUtils/glmnetUtils_{{ version }}.tar.gz


  sha256: 217dcd0ad54fa268f4023aa2cf505649cb4428de26402c8e310536e5f8ec7b29
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, MASS, doParallel, testthat
requirements:
  build:
    - r-base 3.3.2
    - r-matrix 1.2_7.1
    - r-glmnet

  run:
    - r-base 3.3.2
    - r-matrix 1.2_7.1
    - r-glmnet

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('glmnetUtils')"  # [not win]
    - "\"%R%\" -e \"library('glmnetUtils')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/Hong-Revo/glmnetUtils
  license: GPL-2
  summary: Provides a formula interface for the 'glmnet' package for elasticnet regression, a
    method for cross-validating the alpha parameter, and other quality-of-life tools.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: glmnetUtils
# Type: Package
# Version: 1.1
# Title: Utilities for 'Glmnet'
# Description: Provides a formula interface for the 'glmnet' package for elasticnet regression, a method for cross-validating the alpha parameter, and other quality-of-life tools.
# Imports: stats, graphics, grDevices, glmnet, parallel, Matrix
# Suggests: knitr, rmarkdown, MASS, doParallel, testthat
# Author: Microsoft [cph], Hong Ooi [aut, cre]
# Maintainer: Hong Ooi <hongooi@microsoft.com>
# NeedsCompilation: no
# VignetteBuilder: knitr
# Copyright: Microsoft
# License: GPL-2
# URL: https://github.com/Hong-Revo/glmnetUtils
# Collate: 'glmnetUtils.r' 'cvGlmnetFormula.r' 'cvaGlmnetFormula.r' 'glmnetFormula.r' 'makeModelComponents.r'
# RoxygenNote: 6.0.1
# Packaged: 2017-08-01 12:02:41 UTC; hongooi
# Repository: CRAN
# Date/Publication: 2017-08-01 12:37:24 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
