package:
  name: pandas-profiling
  version: "1.4.0"

source:
  fn: pandas-profiling-1.4.0.tar.gz
  url: https://pypi.python.org/packages/b8/91/62dfcd13b3cd773b4a319babd62d5931af6e9931bed142367e71ff0c5f9b/pandas-profiling-1.4.0.tar.gz
  md5: f6cd816607a2627ddb586466f55d1b95
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandas-profiling = pandas-profiling:main
    #
    # Would create an entry point called pandas-profiling that calls pandas-profiling.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas ==0.19.2
    - matplotlib ==2.0.0
    - jinja2 ==2.9.4
    - six ==1.10.0

  run:
    - python
    - pandas ==0.19.2
    - matplotlib ==2.0.0
    - jinja2 ==2.9.4
    - six ==1.10.0

test:
  # Python imports
  imports:
    - pandas_profiling

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/jospolfliet/pandas-profiling
  license: MIT License
  summary: 'Generate profile report for pandas DataFrame'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
