package:
  name: pandas-profiling
  version: "1.4.0"

source:
  fn: pandas-profiling-1.4.0.tar.gz
  url: https://pypi.python.org/packages/b8/91/62dfcd13b3cd773b4a319babd62d5931af6e9931bed142367e71ff0c5f9b/pandas-profiling-1.4.0.tar.gz
  md5: f6cd816607a2627ddb586466f55d1b95

build:
  script: pip install --no-deps .
  number: 2

requirements:
  build:
    - python
    - pandas ==0.20.3
    - matplotlib ==2.0.2
    - jinja2 ==2.9.6
    - six ==1.10.0

  run:
    - python
    - pandas ==0.20.3
    - matplotlib ==2.0.2
    - jinja2 ==2.9.6
    - six ==1.10.0

test:
  imports:
    - pandas_profiling

about:
  home: http://github.com/jospolfliet/pandas-profiling
  license: MIT License
  summary: 'Generate profile report for pandas DataFrame'
  license_family: MIT
