package:
  name: leptonica
  version: 1.74.4

source:
  git_url: https://github.com/DanBloomberg/leptonica
  git_tag: 1.74.4

build:
  number: 1

requirements:
  build:
    - gcc ==5.4.0
    - automake
    - libtool
    - pkg-config
    - jpeg ==8d
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - openjpeg ==2.1.2
    - zlib ==1.2.11
  run:
    - libgcc >=5.4.0
    - jpeg ==8d
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - openjpeg ==2.1.2
    - zlib ==1.2.11

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null

about:
  home: https://github.com/DanBloomberg/leptonica
  summary: "Leptonica image processing library"
  license: BSD
