package:
  name: superset
  version: "0.20.1"

source:
  git_url: https://github.com/apache/incubator-superset
  git_tag: 0.20.1

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - nodejs
    - boto3 ==1.4.4
    - celery ==3.1.25
    - cryptography ==1.9 
    - flask-appbuilder ==1.9.4
    - flask-cache ==0.13.1
    - flask-migrate ==2.0.3
    - flask-script ==2.0.5
    - flask-testing ==0.6.2
    - flower ==0.9.1
    - future ==0.16.0
    - humanize ==0.5.1
    - gunicorn ==19.7.1
    - idna ==2.5
    - markdown ==2.6.8
    - pandas ==0.20.3
    - parsedatetime ==2.0
    - pydruid ==0.3.1
    - pyhive ==0.4.0
    - python-dateutil ==2.6.0
    - requests ==2.17.3
    - simplejson ==3.10.0
    - sqlalchemy-utils ==0.32.16
    - sqlparse ==0.2.3
    - thrift_sasl ==0.2.1
  run:
    - python
    - boto3 ==1.4.4
    - celery ==3.1.25
    - cryptography ==1.9 
    - flask-appbuilder ==1.9.4
    - flask-cache ==0.13.1
    - flask-migrate ==2.0.3
    - flask-script ==2.0.5
    - flask-testing ==0.6.2
    - flower ==0.9.1
    - future ==0.16.0
    - humanize ==0.5.1
    - gunicorn ==19.7.1
    - idna ==2.5
    - markdown ==2.6.8
    - pandas ==0.20.3
    - parsedatetime ==2.0
    - pydruid ==0.3.1
    - pyhive ==0.4.0
    - python-dateutil ==2.6.0
    - requests ==2.17.3
    - simplejson ==3.10.0
    - sqlalchemy-utils ==0.32.16
    - sqlparse ==0.2.3
    - thrift_sasl ==0.2.1

test:
  commands:
    - superset version

about:
  home: https://github.com/apache/incubator-superset
  summary: "modern, enterprise-ready business intelligence web application"
  license: Apache License 2.0
