{% set version = '0.6-00' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-phytools
  version: {{ version|replace("-", "_") }}

source:
  fn: phytools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/phytools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/phytools/phytools_{{ version }}.tar.gz


  sha256: b6c109a6c7b8eecffda6d407173e498948a23bf7320e18633789c4a8673eae13
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: geiger, rgl
requirements:
  build:
    - r-base 3.3.2
    - r-animation 2.5
    - r-ape 4.1
    - r-clustergeneration 1.3.4
    - r-coda 0.18_1
    - r-combinat 0.0_8
    - r-maps 3.1.1
    - r-mnormt 1.5_5
    - r-msm 1.6.4
    - r-nlme 3.1_128
    - r-numderiv 2016.8_1
    - r-phangorn 2.2.0
    - r-plotrix 3.6_5
    - r-scatterplot3d 0.3_40

  run:
    - r-base 3.3.2
    - r-animation 2.5
    - r-ape 4.1
    - r-clustergeneration 1.3.4
    - r-coda 0.18_1
    - r-combinat 0.0_8
    - r-maps 3.1.1
    - r-mnormt 1.5_5
    - r-msm 1.6.4
    - r-nlme 3.1_128
    - r-numderiv 2016.8_1
    - r-phangorn 2.2.0
    - r-plotrix 3.6_5
    - r-scatterplot3d 0.3_40

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('phytools')"  # [not win]
    - "\"%R%\" -e \"library('phytools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/liamrevell/phytools
  license: GPL (>= 2)
  summary: "Package contains various functions for phylogenetic analysis. This functionality
    is concentrated in the phylogenetic analysis of  comparative data from species.
    For example, the package includes functions for Bayesian and ML ancestral state
    estimation; visual simulation of trait evolution; fitting models of trait evolution
    with multiple Brownian rates and correlations; visualizing  discrete and continuous
    character evolution using colors or  projections into trait space; identifying the
    location of a change in the rate of character evolution on the tree; fast Brownian
    motion simulation and simulation under several other models of  continuous trait
    evolution; fitting a model of correlated binary trait evolution; locating the position
    of a fossil or an recently extinct lineage on a tree using continuous character
    data with ML; plotting lineage accumulation through time, including across  multiple
    trees (such as a Bayesian posterior sample); conducting an analysis called stochastic
    character mapping, in which character histories for a discrete trait are sampled
    from their posterior\t probability distribution under a model; conducting a multiple
    \ (i.e., partial) Mantel test; fitting a phylogenetic regression model with error
    in predictor and response variables; conducting a phylogenetic principal components
    analysis, a phylogenetic regression, a reduced major axis regression, a phylogenetic
    canonical correlation analysis, and a phylogenetic ANOVA; projecting  a tree onto
    a geographic map; simulating discrete character  histories on the tree; fitting
    a model in which a discrete character  evolves under the threshold model; visualization
    of cospeciation; and  a simple statistical test for cospeciation between two trees.
    In  addition to this phylogenetic comparative method functionality, the  package
    also contains functions for a wide range of other purposes in  phylogenetic biology.
    For instance, functionality in this package  includes (but is not restricted to):
    adding taxa to a tree  (including randomly, everywhere, or automatically to genera);
    \ generating all bi- and multi-furcating trees for a set of taxa;  reducing a phylogeny
    to its backbone tree; dropping tips or adding  tips to special types of phylogenetic
    trees; exporting a tree as an  XML file; converting a tree with a mapped character
    to a tree with singleton nodes and one character state per edge; estimating a phylogeny
    using the least squares method; simulating birth-death trees under a range of conditions;
    rerooting trees; computing a  consensus tree under multiple methods, including via
    minimization of the distance to other trees in the set; a wide range of  visualizations
    of trees; and a variety of other manipulations and  analyses that phylogenetic biologists
    may find useful for their  research."

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: phytools
# Version: 0.6-00
# Date: 2017-03-28
# Title: Phylogenetic Tools for Comparative Biology (and Other Things)
# Author: Liam J. Revell
# Maintainer: Liam J. Revell <liam.revell@umb.edu>
# Depends: R (>= 3.2.0), ape (>= 4.0), maps
# Imports: animation, clusterGeneration, coda, combinat, graphics, grDevices, methods, mnormt, msm, nlme, numDeriv, phangorn (>= 2.1.1), plotrix, scatterplot3d, stats, utils
# Suggests: geiger, rgl
# ZipData: no
# Description: Package contains various functions for phylogenetic analysis. This functionality is concentrated in the phylogenetic analysis of  comparative data from species. For example, the package includes functions for Bayesian and ML ancestral state estimation; visual simulation of trait evolution; fitting models of trait evolution with multiple Brownian rates and correlations; visualizing  discrete and continuous character evolution using colors or  projections into trait space; identifying the location of a change in the rate of character evolution on the tree; fast Brownian motion simulation and simulation under several other models of  continuous trait evolution; fitting a model of correlated binary trait evolution; locating the position of a fossil or an recently extinct lineage on a tree using continuous character data with ML; plotting lineage accumulation through time, including across  multiple trees (such as a Bayesian posterior sample); conducting an analysis called stochastic character mapping, in which character histories for a discrete trait are sampled from their posterior	 probability distribution under a model; conducting a multiple  (i.e., partial) Mantel test; fitting a phylogenetic regression model with error in predictor and response variables; conducting a phylogenetic principal components analysis, a phylogenetic regression, a reduced major axis regression, a phylogenetic canonical correlation analysis, and a phylogenetic ANOVA; projecting  a tree onto a geographic map; simulating discrete character  histories on the tree; fitting a model in which a discrete character  evolves under the threshold model; visualization of cospeciation; and  a simple statistical test for cospeciation between two trees. In  addition to this phylogenetic comparative method functionality, the  package also contains functions for a wide range of other purposes in  phylogenetic biology. For instance, functionality in this package  includes (but is not restricted to): adding taxa to a tree  (including randomly, everywhere, or automatically to genera);  generating all bi- and multi-furcating trees for a set of taxa;  reducing a phylogeny to its backbone tree; dropping tips or adding  tips to special types of phylogenetic trees; exporting a tree as an  XML file; converting a tree with a mapped character to a tree with singleton nodes and one character state per edge; estimating a phylogeny using the least squares method; simulating birth-death trees under a range of conditions; rerooting trees; computing a  consensus tree under multiple methods, including via minimization of the distance to other trees in the set; a wide range of  visualizations of trees; and a variety of other manipulations and  analyses that phylogenetic biologists may find useful for their  research.
# License: GPL (>= 2)
# URL: http://github.com/liamrevell/phytools
# Packaged: 2017-03-28 19:49:24 UTC; liamj
# Repository: CRAN
# Date/Publication: 2017-03-28 21:11:25 UTC
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
