package:
  name: gcc
  version: 5.4.0

source:
  fn: gcc-5.4.0.tar.gz
  url: ftp://gcc.gnu.org/pub/gcc/releases/gcc-5.4.0/gcc-5.4.0.tar.gz
  md5: f2b4d5a580061711e68f0f506e402e1c

extra:
  gmp:
    source:
      fn: gmp-6.1.0.tar.bz2
      url: ftp://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.bz2
      md5: 86ee6e54ebfc4a90b643a65e402c4048
  mpfr:
    source:
      fn: mpfr-3.1.5.tar.bz2
      url: http://www.mpfr.org/mpfr-current/mpfr-3.1.5.tar.bz2
      md5: b1d23a55588e3b2a13e3be66bc69fd8d
  mpc:
    source:
      fn: mpc-1.0.3.tar.gz
      url: ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
      sha1: b8be66396c726fdc36ebb0f692ed8a8cca3bcc66
  isl:
    source:
      fn: isl-0.16.1.tar.bz2
      url: ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.16.1.tar.bz2
      sha256: 412538bb65c799ac98e17e8cfcdacbb257a57362acfaaff254b0fcae970126d2

build:
  detect_binary_files_with_prefix: False

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
