package:
  name: matplotlib
  version: "2.0.2"

source:
  git_url: https://github.com/matplotlib/matplotlib
  git_tag: v2.0.2

requirements:
  build:
    - python
    - nose
    - pkg-config
    - numpy ==1.13.0
    - python-dateutil ==2.6.0
    - freetype ==2.8
    - cycler ==0.10.0
    - pyparsing ==2.1.4
    - pytz ==2017.3
    - libpng ==1.6.32
    - zlib ==1.2.11
    - tk ==8.5.18
    - icu ==58.2
    - functools32 ==3.2.3.2
    - subprocess32 ==3.2.7
  run:
    - python
    - numpy ==1.13.0
    - python-dateutil ==2.6.0
    - freetype ==2.8
    - cycler ==0.10.0
    - pyparsing ==2.1.4
    - pytz ==2017.3
    - libpng ==1.6.32
    - zlib ==1.2.11
    - tk ==8.5.18
    - icu ==58.2
    - functools32 ==3.2.3.2
    - subprocess32 ==3.2.7

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._cntr
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - matplotlib.backends._tkagg
    - mpl_toolkits
    - pylab

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
