package:
  name: python-levenshtein
  version: "0.12.0"

source:
  fn: python-Levenshtein-0.12.0.tar.gz
  url: https://pypi.python.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz
  md5: e8cde197d6d304bbdc3adae66fec99fb

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - gcc 5.4.0

  run:
    - python
    - libgcc >=5.4.0

test:
  # Python imports
  imports:
    - Levenshtein

about:
  home: http://github.com/ztane/python-Levenshtein
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python extension for computing string edit distances and similarities.'
  license_family: GPL2
