package:
  name: mcl
  version: 14.137

source:
  fn: mcl-14-137.tar.gz
  url: http://micans.org/mcl/src/mcl-14-137.tar.gz
  md5: bc8740456cf51019d0a9ac5eba665bb5
  patches:
    - mcl.patch

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
  run:
    - libgcc    # [not osx]
    - perl 5.22.2.1

test:
  commands:
    - mcl 2>&1 | grep usage > /dev/null
    - mcxdeblast --help

about:
  home: http://micans.org/mcl/
  license: GPLv3
  summary: MCL - a cluster algorithm for graphs
