package:
  name: geopy
  version: "1.11.0"

source:
  fn: geopy-1.11.0.tar.gz
  url: https://pypi.python.org/packages/19/d0/7128146692fb6facb956b07c40f73d7975b9a36bd8381a0cdb0c6a79a0b6/geopy-1.11.0.tar.gz
  md5: b73445dc0069550bbd2b09162f7339b3

build:
  script: pip install --no-deps .
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT License
  summary: 'Python Geocoding Toolbox'
  license_family: MIT
