package:
  name: oauthlib
  version: "2.0.1"

source:
  fn: oauthlib-2.0.1.tar.gz
  url: https://pypi.python.org/packages/d2/4c/5ac894a469e25ebd02f6b3c2adb9f55253e6d1ca1f16a7d247ae6d48b4c8/oauthlib-2.0.1.tar.gz
  md5: d64091c3b5cc2198c5031d95e70eaa9d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oauthlib = oauthlib:main
    #
    # Would create an entry point called oauthlib that calls oauthlib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - oauthlib
    - oauthlib.oauth1
    - oauthlib.oauth1.rfc5849
    - oauthlib.oauth1.rfc5849.endpoints
    - oauthlib.oauth2
    - oauthlib.oauth2.rfc6749
    - oauthlib.oauth2.rfc6749.clients
    - oauthlib.oauth2.rfc6749.endpoints
    - oauthlib.oauth2.rfc6749.grant_types

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - blinker
    - cryptography
    - mock
    - nose
    - pyjwt >=1.0.0
    # - unittest2
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/idan/oauthlib
  license: BSD License
  summary: 'A generic, spec-compliant, thorough implementation of the OAuth request-signing logic'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
