{% set name = "drmaa" %}
{% set version = "0.7.8" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9dc05f1e2c7a56dc0be4065642c46d26c334f6c30d63d0fc534defeac502802b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - gcc ==5.4.0
    - slurm-drmaa ==1.0.7
  run:
    - python
    - libgcc >=5.4.0
    - slurm-drmaa ==1.0.7

about:
  home: https://github.com/pygridtools/drmaa-python
  license: BSD License
  summary: a python DRMAA library
