package:
  name: slurm-drmaa
  version: "1.0.7"

source:
  git_url: https://github.com/natefoo/slurm-drmaa
  git_tag: 1.0.7

requirements:
  build:
    - gcc ==5.4.0
    - automake
    - bison
    - gperf
    - libtool
    - ragel
  run:
    - libgcc >=5.4.0

about:
  home: https://github.com/natefoo/slurm-drmaa
  summary: "DRMAA for Slurm imported from PSNC SVN"
  license: GPLv3
  license_file: COPYING
