package:
  name: dendropy
  version: 4.2.0

source:
  url: https://pypi.python.org/packages/e6/5a/d48c8d3f8100efd5eb6e6142f28bf1c13200e08882e59596369035ebc138/DendroPy-4.2.0.tar.gz
  md5: b9d5ef912b3c48d38b602430f87c3743

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - dendropy

about:
  home: http://dendropy.org/
  license: BSD
  summary: 'A Python library for phylogenetics and phylogenetic computing: reading, writing, simulation, processing and manipulation of phylogenetic trees (phylogenies) and characters.'
