package:
  name: pysam
  version: "0.12.0.1"

source:
  fn: pysam-0.12.0.1.tar.gz
  url: https://pypi.python.org/packages/b9/98/d98b250f98a6b91df71a03083219bec786cdda5408f77997f8ad81d06058/pysam-0.12.0.1.tar.gz
  md5: 06c57ec1e791f7d1197db4f0037f5b7c

build:
  script: pip install --no-deps .
  binary_relocation: False

requirements:
  build:
    - python
    - cython
    - pip
    - gcc
    - xz
    - zlib
    - bzip2 ==1.0.6
  run:
    - python
    - libgcc
    - xz
    - zlib
    - bzip2 ==1.0.6

test:
  imports:
    - pysam

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  summary: Python module for reading and manipulating SAM/BAM/VCF/BCF files
  license_family: MIT
