package:
  name: parallel
  version: "20171022"

source:
  url: http://ftp.wayne.edu/gnu/parallel/parallel-20171022.tar.bz2
  sha256: f7e2bb7467cd3e87c5488e324950f2710e5d6cc9c9b3c33931e71d7a2d08f8a2

requirements:
  build:
  run:
    - perl ==5.26.0

test:
  commands:
    - parallel --version

about:
  home: http://www.gnu.org/software/parallel/
  license: GPLv3
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers
