{% set version = '1.11.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forestfloor
  version: {{ version|replace("-", "_") }}

source:
  fn: forestFloor_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/forestFloor_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/forestFloor/forestFloor_{{ version }}.tar.gz


  sha256: 87dbc3646c38c8f3051f9eeed08f3b54f02429fa0b0074326cb5564c08ee54eb
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, dplyr
requirements:
  build:
    - r-base 3.3.2
    - r-rcpp 0.12.8
    - r-randomforest 4.6_12
    - r-kknn 1.3.1
    - r-rgl 0.96.0
  run:
    - r-base 3.3.2
    - r-rcpp 0.12.8
    - r-randomforest 4.6_12
    - r-kknn 1.3.1
    - r-rgl 0.96.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('forestFloor')"  # [not win]
    - "\"%R%\" -e \"library('forestFloor')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://forestfloor.dk
  license: GPL-2
  summary: Form visualizations of high dimensional mapping structures of random forests and feature contributions.
  license_family: GPL
