package:
  name: pygraphviz
  version: "1.3.1"

source:
  fn: pygraphviz-1.3.1.tar.gz
  url: https://pypi.python.org/packages/98/bb/a32e33f7665b921c926209305dde66fe41003a4ad934b10efb7c1211a419/pygraphviz-1.3.1.tar.gz
  md5: 7f690295dfe77edaa9e552d09d98d279

build:
  number: 1

requirements:
  build:
    - python
    - graphviz ==2.40.1
  run:
    - python
    - graphviz ==2.40.1

about:
  home: http://pygraphviz.github.io
  license: BSD License
  summary: 'Python interface to Graphviz'
  license_family: BSD
