{% set version = '0.999-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-expm
  version: {{ version|replace("-", "_") }}

source:
  fn: expm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/expm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/expm/expm_{{ version }}.tar.gz


  sha256: 38f1e5bfa90f794486789695d0d9e49158c7eb9445dc171dd83dec3d8fa130d6
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, sfsmisc, Rmpfr
requirements:
  build:
    - r-base 3.3.2
    - r-matrix 1.2_7.1
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.3.2
    - r-matrix 1.2_7.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('expm')"  # [not win]
    - "\"%R%\" -e \"library('expm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://R-Forge.R-project.org/projects/expm/
  license: GPL (>= 2)
  summary: Computation of the matrix exponential, logarithm, sqrt, and related quantities.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: expm
# Type: Package
# Title: Matrix Exponential, Log, 'etc'
# Version: 0.999-2
# Date: 2017-03-28
# Author: Vincent Goulet, Christophe Dutang, Martin Maechler, David Firth, Marina Shapira, Michael Stadelmann
# Contact: expm-developers@lists.R-forge.R-project.org
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Description: Computation of the matrix exponential, logarithm, sqrt, and related quantities.
# Depends: Matrix
# Imports: methods
# Suggests: RColorBrewer, sfsmisc, Rmpfr
# BuildResaveData: no
# License: GPL (>= 2)
# URL: http://R-Forge.R-project.org/projects/expm/
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-03-29 07:09:26 UTC; maechler
# Repository: CRAN
# Date/Publication: 2017-03-29 12:17:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
