package:
  name: rsem
  version: 1.3.0

source:
  fn: rsem_1.3.0.tar.gz
  url: https://github.com/deweylab/RSEM/archive/v1.3.0.tar.gz
  md5: 9728161625d339d022130e2428604bf5
  patches:
    - Makefile.patch
 
requirements:
  build:
    - gcc
    - zlib
    - perl 5.22.2.1
  run:
    - libgcc
    - zlib
    - perl 5.22.2.1
    - bowtie ==1.1.2
    - samtools ==1.2

test:
  commands:
    - rsem-calculate-expression --version

about:
  home: http://deweylab.biostat.wisc.edu/rsem/
  license: GPLv3
  summary: RSEM (RNA-Seq by Expectation-Maximization)
