{% set name = 'lfe' %}
{% set version = '2.5-1998' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, igraph, plm, R2Cuba, numDeriv
requirements:
  build:
    - r-base 3.3.2
    - r-formula 1.2_1
    - r-matrix 1.2_7.1
    - r-sandwich 2.3_4
    - r-xtable 1.8_2
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.3.2
    - r-formula 1.2_1
    - r-matrix 1.2_7.1
    - r-sandwich 2.3_4
    - r-xtable 1.8_2

test:

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lfe')"  # [not win]
    - "\"%R%\" -e \"library('lfe')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=lfe
  license: Artistic-2.0
  summary: Transforms away factors with many levels prior to doing an OLS. Useful for estimating
    linear models with multiple group fixed effects, and for estimating linear models
    which uses factors with many levels as pure control variables. Includes support
    for instrumental variables, conditional F statistics for weak instruments, robust
    and multi-way clustered standard errors, as well as limited mobility bias correction.
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: lfe
# Version: 2.5-1998
# Date: 2016-04-18
# Title: Linear Group Fixed Effects
# Author: Simen Gaure, Ragnar Frisch Centre for Economic Research
# Maintainer: Simen Gaure <Simen.Gaure@frisch.uio.no>
# Copyright: 2011-2016, Simen Gaure
# Depends: R (>= 2.15.2), Matrix (>= 1.1-2)
# Imports: Formula, xtable, compiler, utils, methods, sandwich
# Suggests: knitr, igraph, plm, R2Cuba, numDeriv
# VignetteBuilder: knitr
# ByteCompile: yes
# Description: Transforms away factors with many levels prior to doing an OLS. Useful for estimating linear models with multiple group fixed effects, and for estimating linear models which uses factors with many levels as pure control variables. Includes support for instrumental variables, conditional F statistics for weak instruments, robust and multi-way clustered standard errors, as well as limited mobility bias correction.
# License: Artistic-2.0
# Classification/JEL: C13, C23, C60
# Classification/MSC: 62J05, 65F10, 65F50
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-04-18 09:20:05 UTC; sgaure
# Repository: CRAN
# Date/Publication: 2016-04-19 00:34:26

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
