package:
  name: isodate
  version: "0.6.0"

source:
  fn: isodate-0.6.0.tar.gz
  url: https://pypi.python.org/packages/b1/80/fb8c13a4cd38eb5021dc3741a9e588e4d1de88d895c1910c6fc8a08b7a70/isodate-0.6.0.tar.gz
  md5: 0e1203fce27ce65e2d01c5f21c4d428f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - isodate = isodate:main
    #
    # Would create an entry point called isodate that calls isodate.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six ==1.10

  run:
    - python
    - six ==1.10

test:
  # Python imports
  imports:
    - isodate
    - isodate.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gweis/isodate/
  license: BSD License
  summary: 'An ISO 8601 date/time/duration parser and formatter'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
