{% set version = '0.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-auc
  version: {{ version|replace("-", "_") }}

source:
  fn: AUC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/AUC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/AUC/AUC_{{ version }}.tar.gz


  sha256: e705f2c63d336249d19187f3401120d738d42d323fce905f3e157c2c56643766
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base ==3.3.2

  run:
    - r-base ==3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('AUC')"  # [not win]
    - "\"%R%\" -e \"library('AUC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=AUC
  license: GPL (>= 2)
  summary: 'This package includes functions to compute the area under the curve of selected measures:
    The area under the sensitivity curve (AUSEC), the area under the specificity curve
    (AUSPC), the area under the accuracy curve (AUACC), and the area under the receiver
    operating characteristic curve (AUROC). The curves can also be visualized. Support
    for partial areas is provided.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: AUC
# Type: Package
# Title: Threshold independent performance measures for probabilistic classifiers.
# Version: 0.3.0
# Date: 2013-09-30
# Author: Michel Ballings and Dirk Van den Poel
# Maintainer: Michel Ballings <Michel.Ballings@UGent.be>
# Description: This package includes functions to compute the area under the curve of selected measures: The area under the sensitivity curve (AUSEC), the area under the specificity curve (AUSPC), the area under the accuracy curve (AUACC), and the area under the receiver operating characteristic curve (AUROC). The curves can also be visualized. Support for partial areas is provided.
# License: GPL (>= 2)
# ByteCompile: true
# Packaged: 2013-09-30 14:45:12 UTC; mballing
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-09-30 17:41:33

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
