package:
  name: python-dateutil
  version: "2.6.0"

source:
  fn: python-dateutil-2.6.0.tar.gz
  url: https://pypi.python.org/packages/51/fc/39a3fbde6864942e8bb24c93663734b74e281b984d1b8c4f95d64b0c21f6/python-dateutil-2.6.0.tar.gz
  md5: 6e38f91e8c94c15a79ce22768dfeca87
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-dateutil = python-dateutil:main
    #
    # Would create an entry point called python-dateutil that calls python-dateutil.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six ==1.10

  run:
    - python
    - six ==1.10

test:
  # Python imports
  imports:
    - dateutil
    - dateutil.tz
    - dateutil.zoneinfo

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://dateutil.readthedocs.io
  license: BSD License
  summary: 'Extensions to the standard Python datetime module'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
