package:
  name: pytest-runner
  version: "2.11.1"

source:
  fn: pytest-runner-2.11.1.tar.gz
  url: https://pypi.python.org/packages/9e/4d/08889e5e27a9f5d6096b9ad257f4dea1faabb03c5ded8f665ead448f5d8a/pytest-runner-2.11.1.tar.gz
  md5: bdb73eb18eca2727944a2dcf963c5a81
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-runner = pytest-runner:main
    #
    # Would create an entry point called pytest-runner that calls pytest-runner.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm ==1.15.6

  run:
    - python
    - setuptools
    - setuptools_scm ==1.15.6

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT License
  summary: 'Invoke py.test as distutils command with dependency resolution'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
