{% set version = '1.3.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kknn
  version: {{ version|replace("-", "_") }}

source:
  fn: kknn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/kknn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/kknn/kknn_{{ version }}.tar.gz


  sha256: 22840e70ec2afa40371e274b583634c8f6d27149a87253ee411747d5db78f3db
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2
    - r-matrix 1.2_7.1
    - r-igraph 1.0.1

  run:
    - r-base 3.3.2
    - r-matrix 1.2_7.1
    - r-igraph 1.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kknn')"  # [not win]
    - "\"%R%\" -e \"library('kknn')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/KlausVigo/kknn
  license: GPL (>= 2)
  summary: Weighted k-Nearest Neighbors for Classification, Regression and Clustering.
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: kknn
# Title: Weighted k-Nearest Neighbors
# Version: 1.3.1
# Date: 2016-03-26
# Authors@R: c( person("Klaus", "Schliep", email = "klaus.schliep@gmail.com", role = c("aut", "cre")), person("Klaus", "Hechenbichler", role = "aut"), person("Antoine", "Lizee", email = "antoine.lizee@gmail.com", role = "ctb"))
# Description: Weighted k-Nearest Neighbors for Classification, Regression and Clustering.
# Depends: R (>= 2.10)
# Imports: igraph (>= 1.0), Matrix, stats, graphics
# ByteCompile: TRUE
# License: GPL (>= 2)
# NeedsCompilation: yes
# URL: https://github.com/KlausVigo/kknn
# Repository: CRAN
# Packaged: 2016-03-26 18:35:26 UTC; klaus
# Author: Klaus Schliep [aut, cre], Klaus Hechenbichler [aut], Antoine Lizee [ctb]
# Maintainer: Klaus Schliep <klaus.schliep@gmail.com>
# Date/Publication: 2016-03-26 22:02:21

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
