package:
  name: poretools
  version: 0.6.0

source:
  fn: poretools-0.6.0.tar.gz
  url: https://github.com/arq5x/poretools/archive/v0.6.0.tar.gz

requirements:
  build:
    - python
    - setuptools
    - h5py ==2.6.0
    - pandas ==0.19.2
    - matplotlib ==2.0.0
    - seaborn ==0.7.1
  run:
    - python
    - h5py ==2.6.0
    - pandas ==0.19.2
    - matplotlib ==2.0.0
    - seaborn ==0.7.1

test:
  commands:
    - poretools -v

about:
  home: https://github.com/arq5x/poretools
  license: GPL
  summary: 'Toolkit for working with nanopore sequencing data'
