package:
  name: opencv
  version: 3.1.0

source:
  fn: opencv-3.1.0.tar.gz
  url: https://github.com/opencv/opencv/archive/3.1.0.tar.gz
  sha1: 6bbe804d2b5de17cff73a5f56aa025e8b1e7f1fd

build:
  number: 1

requirements:
  build:
    - python
    - gcc 5.4.0 [linux]
    - cmake
    - numpy 1.13.0
    - jpeg 8d
    - libpng 1.6.27
    - libtiff 4.0.6
    - zlib 1.2.8
  run:
    - python
    - libgcc >=5.4.0 [linux]
    - numpy 1.13.0
    - jpeg 8d
    - libpng 1.6.27
    - libtiff 4.0.6
    - zlib 1.2.8

test:
  imports:
    - cv2

about:
  home: http://opencv.org/
  summary: "Open Source Computer Vision Library"
  license: BSD
