package:
  name: myriad
  version: "0.1.4"

source:
  fn: myriad-0.1.4.zip
  url: https://pypi.python.org/packages/93/6a/89cc3d04157c38625786956d22e39f2fcd322754d4812abefa3997306bfd/myriad-0.1.4.zip
  md5: 7b91eb276751a8b84e1f09e4df348668
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - myriad = myriad:main
    #
    # Would create an entry point called myriad that calls myriad.main()

    - myriad = myriad.components:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - myriad

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - myriad --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cjw85/myriad
  license: MIT License
  summary: 'Simple distributed computing.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
