package:
  name: nodejs
  version: 6.13.0

source:
  git_url: https://github.com/nodejs/node
  git_tag: v6.13.0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4

about:
  home: https://nodejs.org/
  summary: a platform for easily building fast, scalable network applications
  license: MIT
  license_file: LICENSE
