package:
  name: libnetcdf
  version: 4.6.0

source:
  url: https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-4.6.0.tar.gz
  md5: d41515e03b0376eebcec0ddc40ef9fe6

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
  host:
    - hdf5 ==1.10.1
    - zlib ==1.2.11
  run:
    - hdf5 ==1.10.1
    - zlib ==1.2.11

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: https://github.com/Unidata/netcdf-c
  summary: The Unidata network Common Data Form
  license: Other
  license_file: COPYRIGHT
