{% set name = "trinity" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v{{ version }}.tar.gz

requirements:
  build:
    - gcc
    - zlib ==1.2.8
  run:
    - libgcc
    - zlib ==1.2.8
    - openjdk ==1.8.0.102

test:
  commands:
    - "Trinity --cite"
    - "align_and_estimate_abundance.pl --help &> /dev/null || [[ \"$?\" == 255 ]]"
    - "abundance_estimates_to_matrix.pl --help &> /dev/null || [[ \"$?\" == 255 ]]"
    - "run_DE_analysis.pl -h &> /dev/null || [[ \"$?\" == 255 ]]"
    - "analyze_diff_expr.pl -h &> /dev/null || [[ \"$?\" == 255 ]]"
    - "PtR --help &> /dev/null || [[ \"$?\" == 255 ]]"
    - "TrinityStats.pl 2>&1 | grep \"usage:\" "
    - "define_clusters_by_cutting_tree.pl 2>&1 | grep \"define K clusters via k-means algorithm\" "

about:
  home: https://github.com/trinityrnaseq/trinityrnaseq/
  license: 'BSD-3-Clause'
  summary: 'Trinity RNA-Seq de novo transcriptome assembly'
