package:
  name: meson
  version: 0.44.0

source:
  git_url: https://github.com/mesonbuild/meson
  git_tag: 0.44.0

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - git
    - ninja ==1.7.2
  run:
    - python
    - ninja ==1.7.2

about:
  home: https://github.com/mesonbuild/meson
  summary: "The Meson Build System"
  license: Apache-2.0
  license_file: COPYING
