{% set name = "apache-libcloud" %}
{% set version = "2.2.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d065d9da8ba192badad3a98c2f6c3ef9dabba45d1318638b9c1bac83f6c3e7a9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - requests
    - pytest-runner
  run:
    - python
    - requests

test:
  imports:
    - libcloud
    - libcloud.backup
    - libcloud.backup.drivers
    - libcloud.common
    - libcloud.compute
    - libcloud.compute.drivers
    - libcloud.container
    - libcloud.container.drivers
    - libcloud.container.utils
    - libcloud.dns
    - libcloud.dns.drivers
    - libcloud.loadbalancer
    - libcloud.loadbalancer.drivers
    - libcloud.storage
    - libcloud.storage.drivers
    - libcloud.test
    - libcloud.test.backup
    - libcloud.test.common
    - libcloud.test.compute
    - libcloud.test.container
    - libcloud.test.dns
    - libcloud.test.loadbalancer
    - libcloud.test.storage
    - libcloud.utils
  requires:
    - mock
    - pytest
    - pytest-runner
    - requests
    - requests_mock

about:
  home: http://libcloud.apache.org/
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
  description: 'UNKNOWN



    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
