
package:
    name: scala
    version: 2.11.11

source:
    fn: scala-2.11.11.tgz
    url: https://downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz
    sha1: 10a37d1eee3b35a51f205047c106f8679372039e

build:
    number: 0

requirements:
    build:
    run:
        - openjdk ==8.0.121

test:
    commands:
        - scalac -help

about:
    home: http://www.scala-lang.org/
    license: 3-clause BSD license
