package:
  name: tesserocr
  version: 2.2.1

source:
  git_url: https://github.com/sirfz/tesserocr
  git_tag: v2.2.1

requirements:
  build:
    - python
    - setuptools
    - cython
    - gcc 5.4.0
    - tesseract 3.05.01
  run:
    - python
    - libgcc >=5.4.0
    - tesseract 3.05.01

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  summary: "A Python wrapper for the tesseract-ocr API"
  license: MIT License
  license_family: MIT
