package:
  name: tesserocr
  version: 2.1.3

source:
  fn: tesserocr-2.1.3.tar.gz
  url: https://github.com/sirfz/tesserocr/archive/v2.1.3.tar.gz

requirements:
  build:
    - python
    - setuptools
    - cython
    - gcc
    - tesseract ==3.05.00
  run:
    - python
    - libgcc
    - tesseract ==3.05.00

test:
  imports:
    - tesserocr

about:
  home: https://github.com/sirfz/tesserocr
  summary: "A Python wrapper for the tesseract-ocr API"
  license: MIT License
  license_family: MIT
