package:
  name: gdal
  version: 1.8.1

source:
  fn: gdal-1.8.1.tar.gz
  url: http://download.osgeo.org/gdal/old_releases/gdal-1.8.1.tar.gz
  md5: b32269893afc9dc9eced45e74e4c6bb4

build:
  number: 1

requirements:
  build:
    - python
    - gcc ==5.4.0
    - numpy ==1.13.0
    - netcdf ==4.4.1.1
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - geotiff ==1.4.1
    - jpeg ==8d
  run:
    - python
    - libgcc >=5.4.0
    - numpy ==1.13.0
    - netcdf ==4.4.1.1
    - libpng ==1.6.32
    - libtiff ==4.0.6
    - geotiff ==1.4.1
    - jpeg ==8d

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo
    - osgeo.gdal_array

about:
  home: http://www.gdal.org/
  license: MIT
  summary: 'Geospatial Data Abstraction Library'
