{% set name = 'rgdal' %}
{% set version = '1.2-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2
    - r-sp 1.2_3
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - gdal 1.8.1

  run:
    - r-base 3.3.2
    - r-sp 1.2_3
    - gdal 1.8.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rgdal')"  # [not win]
    - "\"%R%\" -e \"library('rgdal')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.gdal.org, https://r-forge.r-project.org/projects/rgdal/
  license: GPL (>= 2)
  summary: 'Provides bindings to Frank Warmerdam''s Geospatial Data Abstraction Library (GDAL)
    (>= 1.6.3) and access to projection/transformation operations from the PROJ.4 library.
    The GDAL and PROJ.4 libraries are external to the package, and, when installing
    the package from source, must be correctly installed first. Both GDAL raster and
    OGR vector map data can be imported into R, and GDAL raster data and OGR vector
    data exported. Use is made of classes defined in the sp package. Windows and Mac
    Intel OS X binaries (including GDAL, PROJ.4 and Expat) are provided on CRAN. '

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: rgdal
# Title: Bindings for the Geospatial Data Abstraction Library
# Version: 1.2-5
# Date: 2016-12-15
# Depends: R (>= 2.14.0), methods, sp (>= 1.1-0)
# Imports: grDevices, graphics, stats, utils
# LinkingTo: sp
# Description: Provides bindings to Frank Warmerdam's Geospatial Data Abstraction Library (GDAL) (>= 1.6.3) and access to projection/transformation operations from the PROJ.4 library. The GDAL and PROJ.4 libraries are external to the package, and, when installing the package from source, must be correctly installed first. Both GDAL raster and OGR vector map data can be imported into R, and GDAL raster data and OGR vector data exported. Use is made of classes defined in the sp package. Windows and Mac Intel OS X binaries (including GDAL, PROJ.4 and Expat) are provided on CRAN.
# Authors@R: c( person("Roger", "Bivand", role = c("cre", "aut"), email = "Roger.Bivand@nhh.no"), person("Tim", "Keitt", role = "aut"), person("Barry", "Rowlingson", role = c("aut", "ctb")), person("Edzer", "Pebesma", role = "ctb"), person("Michael", "Sumner", role = "ctb"), person("Robert", "Hijmans", role = "ctb"), person("Even", "Rouault", role = "ctb"))
# License: GPL (>= 2)
# URL: http://www.gdal.org, https://r-forge.r-project.org/projects/rgdal/
# SystemRequirements: for building from source: GDAL >= 1.6.3, library from http://trac.osgeo.org/gdal/wiki/DownloadSource and PROJ.4 (proj >= 4.4.9) from http://download.osgeo.org/proj/; GDAL OSX frameworks built by William Kyngesburye at http://www.kyngchaos.com/ may be used for source installs on OSX.
# NeedsCompilation: yes
# Packaged: 2016-12-15 11:39:17 UTC; rsb
# Author: Roger Bivand [cre, aut], Tim Keitt [aut], Barry Rowlingson [aut, ctb], Edzer Pebesma [ctb], Michael Sumner [ctb], Robert Hijmans [ctb], Even Rouault [ctb]
# Maintainer: Roger Bivand <Roger.Bivand@nhh.no>
# Repository: CRAN
# Date/Publication: 2016-12-15 13:53:02

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
