{% set name = 'modeltools' %}
{% set version = '0.2-21' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2

  run:
    - r-base 3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modeltools')"  # [not win]
    - "\"%R%\" -e \"library('modeltools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=modeltools
  license: GPL-2
  summary: A collection of tools to deal with statistical models.  The functionality is experimental
    and the user interface is likely to change in the future. The documentation is rather
    terse, but packages `coin' and `party' have some working examples. However, if you
    find the implemented ideas interesting we would be very interested in a discussion
    of this proposal. Contributions are more than welcome!
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: modeltools
# Title: Tools and Classes for Statistical Models
# Date: 2013-09-02
# Version: 0.2-21
# Author: Torsten Hothorn, Friedrich Leisch, Achim Zeileis
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Description: A collection of tools to deal with statistical models.  The functionality is experimental and the user interface is likely to change in the future. The documentation is rather terse, but packages `coin' and `party' have some working examples. However, if you find the implemented ideas interesting we would be very interested in a discussion of this proposal. Contributions are more than welcome!
# Depends: stats, stats4
# Imports: methods
# LazyLoad: yes
# License: GPL-2
# Packaged: 2013-09-02 11:15:31 UTC; hothorn
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-09-02 14:29:21

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
