package:
  name: et_xmlfile
  version: "1.0.1"

source:
  fn: et_xmlfile-1.0.1.tar.gz
  url: https://pypi.python.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
  md5: f47940fd9d556375420b2e276476cfaf
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - et_xmlfile = et_xmlfile:main
    #
    # Would create an entry point called et_xmlfile that calls et_xmlfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - et_xmlfile
    - et_xmlfile.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/openpyxl/et_xmlfile
  license: MIT License
  summary: 'An implementation of lxml.xmlfile for the standard library'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
