package:
  name: linear-tsv
  version: "1.1.0"

source:
  fn: linear-tsv-1.1.0.tar.gz
  url: https://pypi.python.org/packages/82/e5/03207a0f11e1d60df85b97b61704ed701b725a7c2feaf83f7bfbd0c2d83e/linear-tsv-1.1.0.tar.gz
  md5: 7053a4314b91d672c8114f80e4fbb520
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - linear-tsv = linear-tsv:main
    #
    # Would create an entry point called linear-tsv that calls linear-tsv.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six ==1.10

  run:
    - python
    - six ==1.10

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/solidsnack/tsv
  license: Apache Software License
  summary: 'Line-oriented, tab-separated value format'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
