package:
  name: eralchemy
  version: "1.1.0"

source:
  fn: ERAlchemy-1.1.0.tar.gz
  url: https://pypi.python.org/packages/f8/84/a7e4b73a427425e8d2d0446b6e94320e7ab4c44abe29c66150a7ee14f981/ERAlchemy-1.1.0.tar.gz
  md5: 8bc350128203ef59b63c5d4fae203bdc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - eralchemy = eralchemy:main
    #
    # Would create an entry point called eralchemy that calls eralchemy.main()

    - eralchemy=eralchemy.main:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sqlalchemy ==1.1.5
    - pygraphviz ==1.3.1

  run:
    - python
    - sqlalchemy ==1.1.5
    - pygraphviz ==1.3.1

test:
  # Python imports
  imports:
    - eralchemy

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - eralchemy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Alexis-benoist/eralchemy
  license: Apache License 2.0
  summary: 'Simple entity relation (ER) diagrams generation'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
