package:
  name: eralchemy
  version: "1.1.0"

source:
  fn: ERAlchemy-1.1.0.tar.gz
  url: https://pypi.python.org/packages/f8/84/a7e4b73a427425e8d2d0446b6e94320e7ab4c44abe29c66150a7ee14f981/ERAlchemy-1.1.0.tar.gz
  md5: 8bc350128203ef59b63c5d4fae203bdc

build:
  script: pip install --no-deps .
  entry_points:
    - eralchemy=eralchemy.main:cli
  number: 1

requirements:
  build:
    - python
    - sqlalchemy ==1.1.9
    - pygraphviz ==1.3.1

  run:
    - python
    - sqlalchemy ==1.1.9
    - pygraphviz ==1.3.1

test:
  # Python imports
  imports:
    - eralchemy

  commands:
    - eralchemy --help

about:
  home: https://github.com/Alexis-benoist/eralchemy
  license: Apache License 2.0
  summary: 'Simple entity relation (ER) diagrams generation'
  license_family: APACHE
