{% set version = '0.0-8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-combinat
  version: {{ version|replace("-", "_") }}

source:
  fn: combinat_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/combinat_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/combinat/combinat_{{ version }}.tar.gz


  sha256: 1513cf6b6ed74865bfdd9f8ca58feae12b62f38965d1a32c6130bef810ca30c1
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.3.2

  run:
    - r-base 3.3.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('combinat')"  # [not win]
    - "\"%R%\" -e \"library('combinat')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=combinat
  license: GPL-2
  summary: routines for combinatorics
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: combinat
# Version: 0.0-8
# Title: combinatorics utilities
# Author: Scott Chasalow
# Maintainer: Vince Carey <stvjc@channing.harvard.edu>
# Description: routines for combinatorics
# License: GPL-2
# Repository: CRAN
# Date/Publication: 2012-10-29 08:58:26
# Packaged: 2012-10-29 08:58:26 UTC; ripley
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
