package:
  name: netcdf
  version: 4.4.1.1

source:
  fn: netcdf-4.4.1.1.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v4.4.1.1.tar.gz
  md5: 9210fd5355bee868684d9b8f83064aa6

build:
  number: 1

requirements:
  build:
    - gcc ==5.4.0
    - hdf5 ==1.8.17
    - zlib ==1.2.11
  run:
    - libgcc >=5.4.0
    - hdf5 ==1.8.17
    - zlib ==1.2.11

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: https://github.com/Unidata/netcdf-c
  license: MIT
  summary: "The Unidata network Common Data Form"
