{% set version = '1.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prettyunits
  version: {{ version|replace("-", "_") }}

source:
  fn: prettyunits_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/prettyunits_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/prettyunits/prettyunits_{{ version }}.tar.gz


  sha256: 35a4980586c20650538ae1e4fed4d80fdde3f212b98546fc3c7d9469a1207f5c
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r-base 3.3.2
    - r-assertthat 0.1
    - r-magrittr 1.5

  run:
    - r-base 3.3.2
    - r-assertthat 0.1
    - r-magrittr 1.5

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('prettyunits')"  # [not win]
    - "\"%R%\" -e \"library('prettyunits')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/gaborcsardi/prettyunits
  license: MIT + file LICENSE
  summary: 'Pretty, human readable formatting of quantities. Time intervals: 1337000 -> 15d 11h
    23m 20s. Vague time intervals: 2674000 -> about a month ago. Bytes: 1337 -> 1.34
    kB.'

  license_family: MIT

# The original CRAN metadata for this package was:

# Package: prettyunits
# Title: Pretty, Human Readable Formatting of Quantities
# Version: 1.0.2
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Pretty, human readable formatting of quantities. Time intervals: 1337000 -> 15d 11h 23m 20s. Vague time intervals: 2674000 -> about a month ago. Bytes: 1337 -> 1.34 kB.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/gaborcsardi/prettyunits
# BugReports: https://github.com/gaborcsardi/prettyunits/issues
# Imports: magrittr, assertthat, methods
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2015-07-13 02:03:57 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2015-07-13 04:09:56

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
