package:
  name: perl-scalar-list-utils
  version: 1.45

source:
  fn: Scalar-List-Utils-1.45.tar.gz
  url: https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.45.tar.gz
  md5: b469e990ec92a4c9386aaf9e92857ae9

requirements:
  build:
    - gcc
    - perl 5.22.2.1
  run:
    - libgcc
    - perl 5.22.2.1

test:
  imports:
    - Scalar::Util

about:
  home: http://metacpan.org/pod/Scalar-List-Utils
  license: perl_5
  summary: 'Common Scalar and List utility subroutines'
