package:
  name: samtools
  version: 1.2

source:
  url: https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2
  sha1: 57b7c9b048c1081f6d5f7955c10724f6065380bd
  patches:
    - Makefile.patch

requirements:
  build:
  - gcc  # [not osx]
  - llvm # [osx]
  - zlib
  - curl
  run:
  - libgcc # [not osx]
  - perl 5.22.2.1
  - zlib
  - curl

test:
  commands:
    - samtools --help

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: Tools for dealing with SAM, BAM and CRAM files
