{% set name = 'lattice' %}
{% set version = '0.20-35' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: KernSmooth, MASS, latticeExtra
requirements:
  build:
    - r-base 3.1.2
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.1.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lattice')"  # [not win]
    - "\"%R%\" -e \"library('lattice')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://lattice.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: A powerful and elegant high-level data visualization system inspired by Trellis graphics,
    with an emphasis on multivariate data. Lattice is sufficient for typical graphics
    needs, and is also flexible enough to handle most nonstandard requirements. See
    ?Lattice for an introduction.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: lattice
# Version: 0.20-35
# Date: 2017-03-23
# Priority: recommended
# Title: Trellis Graphics for R
# Author: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Maintainer: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Description: A powerful and elegant high-level data visualization system inspired by Trellis graphics, with an emphasis on multivariate data. Lattice is sufficient for typical graphics needs, and is also flexible enough to handle most nonstandard requirements. See ?Lattice for an introduction.
# Depends: R (>= 3.0.0)
# Suggests: KernSmooth, MASS, latticeExtra
# Imports: grid, grDevices, graphics, stats, utils
# Enhances: chron
# LazyLoad: yes
# LazyData: yes
# License: GPL (>= 2)
# URL: http://lattice.r-forge.r-project.org/
# BugReports: https://github.com/deepayan/lattice/issues
# NeedsCompilation: yes
# Packaged: 2017-03-25 11:25:40 UTC; deepayan
# Repository: CRAN
# Date/Publication: 2017-03-25 18:05:47 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
